#My sketches

[workspace]
members = [
	"svg",
	"ray2d",
	"edapx-colors",
	"lines-vector",
	"polyline",
	"pattern_2",
	"patternone",
	"rayquad",
	"rayquad2",
	"rayquad3",
	"raycircle",
	"raycircle2",
	"screeneffect",
	"svg-easy",
	"template-quad"
]

[profile.release]
debug = true
