[package]
name = "screeneffect"
version = "0.1.0"
authors = ["Davide Prati"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = { version ="0.18.0"  }
nannou_conrod = { version ="0.18.0" }
